pipeline {
    agent any 

    tools {
        maven 'maven_tool'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url: 'http://3.144.169.57:8081/')], 
                                     contextPath: '/itdefined-war-1.0.0', 
                                     war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }

}
